version: '3.7'

services:
    postgres:
        container_name: cache_register_postgres
        image: postgres:13.1
        networks:
            - backend
        environment:
            POSTGRES_PASSWORD: cache_register
            POSTGRES_USER: cache_register
            POSTGRES_DB: cache_register
        ports:
            - 5439:5439
        expose:
            - 5439
        command: -p 5439
    
    main:
        container_name: cache_register_main
        build:
            context: "./"
        environment:
            - NODE_ENV=development
        restart: always
        ports:
            - 8181:6000
        command: sh -c "sleep 5 && echo RADI BAKI && php -S localhost:8181"
        volumes:
            - ./:/usr/src/app
        networks:
            - backend
        depends_on:
            - postgres

networks:
    backend:
        driver: bridge