version: '3.7'

services:
    php-apache-environment:
        container_name: php-apache
        build: .
        networks:
            - backend
        image: php:8.0-apache
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
        depends_on:
            - postgres
    postgres:
        container_name: cacheRegisterPostgres
        image: postgres:13.1
        networks:
            - backend
        environment:
            POSTGRES_PASSWORD: cache_register
            POSTGRES_USER: cache_register
            POSTGRES_DB: cache_register
        ports:
            - 5439:5439
        expose:
            - 5439
        command: -p 5439

networks:
    backend:
        driver: bridge